server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    filter:
      order: 0
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    template:
      max-message-size: 157286400 # 150 MB
    listener:
      type: simple
      simple:
        max-message-size: 157286400 # 150 MB
        message-converter: jackson2JsonMessageConverter
  cloud:
    openfeign:
      client:
        config:
          megamind:
            connectTimeout: 5000 # 5 sec
            readTimeout: 5000 # 5 sec
            loggerLevel: basic
            errorDecoder: ru.visionary.mixing.mind_broker.client.error.MegamindErrorDecoder
            url: ${MEGAMIND_URL}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: PT15M
    refresh-token-expiration: P30D
  minio:
    endpoint: ${MINIO_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    images-bucket: images
    avatars-bucket: avatars
  rabbit:
    processing-exchange: image.processing
    processing-queue: image-processing
    processed-exchange: image.processed
    processed-queue-prefix: processed-
    processed-queue-expires: 1800000 # 30 min
  processing:
    max-time-from-start: PT10M
    compression:
      enabled: true
      quality: 0.75
      max-width: 1920
      max-height: 1920
      min-length: 1048576 # 1 MB
  megamind:
    api-key: ${MEGAMIND_API_KEY}
    processing-timeout: 150 # 2 min 30 sec
    update-styles-job-cron: 0 0/15 * * * *

management:
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.request: 0.80,0.95,0.99
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    ru.visionary.mixing: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO