name: Deploy release

on:
  push:
    branches: ['release/**']

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build package
        run: mvn -B clean package -DskipTests

      - name: Upload artifacts to VM
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
          SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > key
          chmod 600 key

          scp -i key \
            target/mind-broker.jar \
            Dockerfile \
            $VM_USER@$VM_IP:/mind-broker/

      - name: Run migrations and deploy
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
          SSH_KEY: ${{ secrets.VM_SSH_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "$SSH_KEY" > key
          chmod 600 key
          ssh -i key $VM_USER@$VM_IP /bin/bash -s -- \
            "$DB_URL" \
            "$DB_USERNAME" \
            "$DB_PASSWORD" \
            "$JWT_SECRET" << 'EOF'

            cd /mind-broker

            DB_URL=$1
            DB_USERNAME=$2
            DB_PASSWORD=$3
            JWT_SECRET=$4

            docker build -t mind-broker:latest .

            docker run --rm \
              -e SPRING_DATASOURCE_URL="$DB_URL" \
              -e SPRING_DATASOURCE_USERNAME="$DB_USERNAME" \
              -e SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
              -e JWT_SECRET="$JWT_SECRET" \
              -e SPRING_MAIN_WEB-APPLICATION-TYPE=none \
              mind-broker:latest || exit 1

            echo "Migration completed"
  
            docker stop mind-broker || true
            docker rm mind-broker || true

            docker run -d \
              --name mind-broker \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL="$DB_URL" \
              -e SPRING_DATASOURCE_USERNAME="$DB_USERNAME" \
              -e SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
              -e JWT_SECRET="$JWT_SECRET" \
              mind-broker:latest

            echo "Deployment completed successfully"
          EOF
