name: Deploy release

on:
  push:
    branches: ['release/**']

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build package
        run: mvn -B clean package -DskipTests

      - name: Upload artifacts to VM
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
          SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > key
          chmod 600 key

          scp -i key \
            target/mind-broker.jar \
            Dockerfile \
            $VM_USER@$VM_IP:/mind-broker/

      - name: Run migrations and deploy
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_IP: ${{ secrets.VM_IP }}
          SSH_KEY: ${{ secrets.VM_SSH_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MINIO_URL: ${{ secrets.MINIO_URL }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          MEGAMIND_URL: ${{ secrets.MEGAMIND_URL }}
          MEGAMIND_API_KEY: ${{ secrets.MEGAMIND_API_KEY }}
        run: |
          echo "$SSH_KEY" > key
          chmod 600 key
          ssh -i key $VM_USER@$VM_IP /bin/bash -s -- \
            "$DB_URL" \
            "$DB_USERNAME" \
            "$DB_PASSWORD" \
            "$JWT_SECRET" \
            "$MINIO_URL" \
            "$MINIO_ACCESS_KEY" \
            "$MINIO_SECRET_KEY" \
            "$RABBIT_HOST" \
            "$RABBIT_USERNAME" \
            "$RABBIT_PASSWORD" \
            "$MEGAMIND_URL" \
            "$MEGAMIND_API_KEY" << 'EOF'

            cd /mind-broker

            DB_URL=${1}
            DB_USERNAME=${2}
            DB_PASSWORD=${3}
            JWT_SECRET=${4}
            MINIO_URL=${5}
            MINIO_ACCESS_KEY=${6}
            MINIO_SECRET_KEY=${7}
            RABBIT_HOST=${8}
            RABBIT_USERNAME=${9}
            RABBIT_PASSWORD=${10}
            MEGAMIND_URL=${11}
            MEGAMIND_API_KEY=${12}

            docker build -t mind-broker:latest .

            docker run --rm \
              -e SPRING_PROFILES_ACTIVE="migrations" \
              -e SPRING_DATASOURCE_URL="$DB_URL" \
              -e SPRING_DATASOURCE_USERNAME="$DB_USERNAME" \
              -e SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
              -e JWT_SECRET="$JWT_SECRET" \
              -e MINIO_URL="$MINIO_URL" \
              -e MINIO_ACCESS_KEY="$MINIO_ACCESS_KEY" \
              -e MINIO_SECRET_KEY="$MINIO_SECRET_KEY" \
              -e RABBIT_HOST="$RABBIT_HOST" \
              -e RABBIT_USERNAME="$RABBIT_USERNAME" \
              -e RABBIT_PASSWORD="$RABBIT_PASSWORD" \
              -e MEGAMIND_URL="$MEGAMIND_URL" \
              -e MEGAMIND_API_KEY="$MEGAMIND_API_KEY" \
              -e SPRING_MAIN_WEB-APPLICATION-TYPE=none \
              mind-broker:latest migrations || exit 1

            echo "Migration completed"
  
            docker stop mind-broker || true
            docker rm mind-broker || true

            docker run -d \
              --name mind-broker \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL="$DB_URL" \
              -e SPRING_DATASOURCE_USERNAME="$DB_USERNAME" \
              -e SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD" \
              -e JWT_SECRET="$JWT_SECRET" \
              -e MINIO_URL="$MINIO_URL" \
              -e MINIO_ACCESS_KEY="$MINIO_ACCESS_KEY" \
              -e MINIO_SECRET_KEY="$MINIO_SECRET_KEY" \
              -e RABBIT_HOST="$RABBIT_HOST" \
              -e RABBIT_USERNAME="$RABBIT_USERNAME" \
              -e RABBIT_PASSWORD="$RABBIT_PASSWORD" \
              -e MEGAMIND_URL="$MEGAMIND_URL" \
              -e MEGAMIND_API_KEY="$MEGAMIND_API_KEY" \
              mind-broker:latest

            echo "Deployment completed successfully"
          EOF
